project:
  type: website
  output-dir: docs
  render:
    - "src/*.qmd" # This tells Quarto to render all .qmd files directly in the root folder
  resources:
    - heatmap.csv
    - src/assets/**



website:
  title: "OpenDengue"
  favicon: "src/assets/logo/favicon_v2.ico"
  page-footer:
    center: |
      © Copyright 2025 the OpenDengue project<br>
      The Dengue Mapping and Modelling Group<br>
      LSHTM, London UK<br>
      <br>
      Content licensed under <a href="http://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.

  navbar:
    logo: "src/assets/logo/logo3_v2.png"
    logo-href: "https://opendengue.org/index.html"
    left:
      - text: "Home"
        href: src/index.qmd
      - text: "Data"
        href: src/data.qmd
      - text: "Project"
        href: src/project.qmd
      - text: "Methods"
        href: src/overview.qmd
      - text: "Contribute"
        href: src/contribute.qmd
      - icon: github
        href: "https://github.com/OpenDengue/master-repo"

format:
  html:
    theme: flatly
    css: styles.css
